apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "yace.fullname" . }}
  labels:
    {{- include "yace.labels" . | nindent 4 }}
data:
{{- with .Values.config }}
  config.yml: |-
{{ toYaml . | indent 4 }}
{{- end }}
